### PR TITLE
Use the native cxx11 initializer, the boost one seems incompatible with cxx11

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by doudou** [comment]
This starts to get too far.

There are issues with mixing C++11 and C++08. https://gcc.gnu.org/wiki/Cxx11AbiCompatibility. I would be very much surprised that we won't hit some of them in e.g. boost which is in the end very different between C++11 and C++98 mode.

Requiring C++11 in packages because they don't build under C++11 is a definite no-no for me. It would sound a lot safer to force C++98 mode in these packages even if a global flag tries to compile with C++11. As dangerous (since you're still mixing), but at least you don't break C++98-using people.

**Comment by goldhoorn** [comment]
Ehm,
There are several base-packages for the pddl_planner that already only 
wokring with cxx11 (See other PRs). Therefore the easiiest way here is 
to use cxx11 for this package too.
Therefore this package is only Availible if only-cxx11-packages were 
build. there is no reason to stick to the 98 mode here.

This is the only way to preventing such problems of mixing ABIs, because 
the prior packages need cxx11. Maybe we can add a option that the 
complete rock build enables cxx11 (nicer then exporting ENVs). But in 
the end we need cxx11 here....

In general:
I see absolutly no reason why whe should forbit the usage of cxx11 packages.
We cannot stick to the past forever.

FYI: i build (epext the orientation estimator which is creepy partwise) 
completly with clang and cxx11 locally.

**Comment by doudou** [comment]
> There are several base-packages for the pddl_planner that already only wokring with cxx11 (See other PRs). Therefore the easiiest way here is to use cxx11 for this package too.

Fair enough. I missed that one.

> I see absolutly no reason why whe should forbit the usage of cxx11 packages. We cannot stick to the past forever.

We should definitely not forbid its usage. But one should not *force* its usage either. Last discussion (started by Leif) went nowhere conclusive. And we should obviously have a proper testing period.

I actually appreciate that you are trying to allow compiling Rock in C++11 mode. That would be great, because it will allow for testing. 

Switching to C++11 is not hassle-free. Compilation is not the issue, weird duplicate symbols because one mixes C++98 shared libraries from the OS packages and C++11 ones from the local compilation *is*. Having spent two days debugging an issue like this (a boost class that was ABI-incompatible in debug and non-debug modes) I can tell you that it is NOT fun.

**Comment by goldhoorn** [comment]
Sure then specialliy with a eye to my PR on the base types PR 
(https://github.com/rock-core/base-cmake/pull/11)

Is this fine enought or should we create a define for cmake that can be 
setted and enables cxx11 for ALL packages?
This should not used for debugging/development purposes but would make 
the usage better

i have in mind something like

if(ROCK_USE_CXX11)
rock_activate_cxx11()
endif()

in rock_init of Rock.cmake

**Comment by jmachowinski** [comment]
+1 for enabling c++11 by default.
I used it lately a lot in my packages.

**Comment by jmachowinski** [comment]
btw most ABI issues don't apply (at least for std), because 14.04 already uses GCC 4.8.2.

**Comment by doudou** [comment]
> This should not used for debugging/development purposes but would make the usage better

@goldhoorn: I would definitely +1 that. The last problematic bit with having C++11 on by default is to field-test the clang importer, but having a nice way to test it would be great.

**Comment by goldhoorn** [comment]
Updated https://github.com/rock-core/base-cmake/pull/11

recommend move the discussion to there...

**Comment by goldhoorn** [comment]
@2maz please merge (rock macros got accepted)

**Comment by 2maz** [comment]
One minor change pls: can you align of the brackets, i.e. first an last should be on the same indentation level. thx

**Comment by goldhoorn** [comment]
done *updated*

**Comment by 2maz** [comment]
Thx, merged

**Pull request merged**
